version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /certs:/certs
  welcome:
    build: ./welcome
  hive-node:
    build:
      context: ./
      dockerfile: hive-node/Dockerfile
